# Generated by Django 5.1 on 2024-08-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='field1',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='field10',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='field2',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='field3',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='field4',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='field5',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='field6',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='field7',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='field8',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='field9',
        ),
        migrations.AddField(
            model_name='formdata',
            name='Calcium',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='Climate',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='Crop',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='Iron',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='Magnesium',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='Nitrogen',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='O2_Level',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='Phosphorous',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='Potassium',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='Rainfall',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='Soil_Type',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
